In [1]:
import numpy as np
from dokusan import generators

random_sudoku = generators.random_sudoku(avg_rank=10)
sudoku_grid = np.array(random_sudoku)
sudoku_grid = np.array(list(str(random_sudoku)))
sudoku_grid = sudoku_grid.reshape(9,9).astype(int)
# print(sudoku_grid)
# Now sudoku_grid is a 9x9 NumPy array
print(sudoku_grid)

[[9 4 2 0 0 6 5 7 8]
 [5 0 0 8 9 0 1 3 4]
 [0 8 3 4 5 7 9 0 0]
 [2 0 4 3 8 9 6 5 7]
 [8 0 5 6 0 1 2 4 3]
 [3 7 6 2 4 0 8 1 9]
 [0 2 8 9 1 3 7 6 5]
 [6 5 9 7 0 4 3 8 0]
 [7 3 1 0 6 8 4 9 2]]


In [2]:

#lets first check which numbers are missing at the given (row, col) coordinate
# small grids to find out which numbers are potential candidates 

def is_candidate(sudoku_grid, row, col, value):
    # assert sudoku_grid[row, col] == 0, "cannot test non-empty"
    assert sudoku_grid.dtype == np.int64, sudoku_grid.dtype
    assert type(value) == int, type(value)
    
    
    # i want to check if a value is already present in the given row
    if value in sudoku_grid[row,:]:
        return False
    # i want to check if a value is already present in the given column
    if value in sudoku_grid[:,col]:
        return False
        
        #let us define a subgrid
                
    row_start, col_start = row - row%3, col - col%3
    subgrid = sudoku_grid[row_start:row_start+3,col_start:col_start+3]
    if value in subgrid:
        return False
    
    return True
        
is_candidate(sudoku_grid, 0, 0, 1)

def assert_is_candidate(grid, row, col, value):
    assert is_candidate(grid, row, col, value),\
        f"value {value} at ({row}, {col}) is not a candidate"
    
def assert_not_is_candidate(grid, row, col, value):
    assert not is_candidate(grid, row, col, value),\
        f"value {value} at ({row}, {col}) is a candidate"

# Test is_candidate
def test_is_candidate():
    test_grid = np.array([
        ['5', '0', '4', '0', '8', '0', '1', '0', '0'],
        ['0', '3', '1', '9', '0', '0', '8', '0', '7'],
        ['9', '0', '0', '0', '0', '0', '0', '0', '0'],
        ['0', '0', '3', '0', '0', '0', '0', '0', '0'],
        ['0', '0', '5', '2', '0', '6', '0', '1', '0'],
        ['6', '0', '0', '3', '5', '0', '0', '8', '2'],
        ['0', '0', '0', '0', '6', '0', '0', '5', '1'],
        ['4', '5', '0', '0', '0', '0', '6', '0', '0'],
        ['0', '0', '0', '0', '0', '0', '0', '9', '8']]).astype(int)
    assert_is_candidate(test_grid, 1,0,2)
    assert_not_is_candidate(test_grid, 1,0,6)
    assert_is_candidate(test_grid,3,1,4)
    assert_not_is_candidate(test_grid,3,1,3)
    print("SUCCESS")

test_is_candidate()
        


SUCCESS


In [3]:
# find the next empty cell returning its coordinates 
# and if no empty cell, return 'None'
# cell is not empty means the cell !=0
# if all the cells are not empty, means that the sudoku grid is solved

def next_empty(grid):
    for row in range(9):
        for col in range(9):
            if grid[row, col] == 0:
                return(row, col)

    return None
                
next_empty(sudoku_grid)

a = sudoku_grid
next_empty(a)

(0, 3)

In [4]:
def solve_sudoku(grid):
    assert type(grid) is np.ndarray, 'is not ndarray'
    empty_cell = next_empty(grid)
    
    # there are no more empty cells in the grid, return the solved grid
    if empty_cell is None:
        return grid
    assert empty_cell is not None, 'we should have returned a solved'
    assert type(empty_cell) is tuple, 'is not a tuple'
    row, col = empty_cell

    for value in range(1,10):
        if is_candidate(grid, row, col, value):
            grid_copy = np.copy(grid)
            grid_copy[row][col] = value
            # print(f"candidate for {row},{col},{value}")

            maybe_solved = solve_sudoku(grid_copy)
            if maybe_solved is None:
                continue
            assert type(maybe_solved) is np.ndarray,\
            f'expected: np.ndarray, found: {type(maybe_solved)}'
            return maybe_solved
    
    return None
        
solve_sudoku(sudoku_grid)

array([[9, 4, 2, 1, 3, 6, 5, 7, 8],
       [5, 6, 7, 8, 9, 2, 1, 3, 4],
       [1, 8, 3, 4, 5, 7, 9, 2, 6],
       [2, 1, 4, 3, 8, 9, 6, 5, 7],
       [8, 9, 5, 6, 7, 1, 2, 4, 3],
       [3, 7, 6, 2, 4, 5, 8, 1, 9],
       [4, 2, 8, 9, 1, 3, 7, 6, 5],
       [6, 5, 9, 7, 2, 4, 3, 8, 1],
       [7, 3, 1, 5, 6, 8, 4, 9, 2]])